### ISSUE TITLE
缓存的时候崩溃 Invalid parameter not satisfying: URL.host

### ISSUE THREAD

**Issue by dbmbeijing** [changsanjiang/SJMediaCacheServer#29]
请问这个怎么处理呀  Invalid parameter not satisfying: URL.host

**Comment by changsanjiang** [comment]
奔溃日志看看

**Comment by J0nphy** [comment]
同样的问题，而且高频出现

**Comment by J0nphy** [comment]
*** Assertion failure in -[MCSURL assetNameForURL:], MCSURL.m:92
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: URL.host'
*** First throw call stack:
(0x18b39a69c 0x183657c80 0x18a8f8dd8 0x1080b64a4 0x1080a6cd8 0x1080a73c0 0x108074090 0x109aa2b34 0x109ab40b4 0x1080b4f3c 0x108073efc 0x1080b0f54 0x18a2bfa9c 0x18a2bf808 0x109aa0f50 0x109aa2b34 0x109aa5c20 0x109aa4ef8 0x109ab6cd8 0x109ab76cc 0x1f5293928 0x1f5293a04)
[Bugly]  Trapped uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid parameter not satisfying: URL.host' 
[
  "0   CoreFoundation                      0x000000018b39a6a8 BE405D8A-5464-37A3-A17E-1068DB404B23 + 968360",
  "1   libobjc.A.dylib                     0x0000000183657c80 objc_exception_throw + 60",
  "2   Foundation                          0x000000018a8f8dd8 C52A9630-60F1-3D48-A6C3-50A20DE78C6A + 7015896",
  "3   SJMediaCacheServer                  0x00000001080b64a4 -[MCSURL assetNameForURL:] + 308",
  "4   SJMediaCacheServer                  0x00000001080a6cd8 -[MCSAssetManager assetWithURL:] + 160",
  "5   SJMediaCacheServer                  0x00000001080a73c0 -[MCSAssetManager readerWithRequest:networkTaskPriority:delegate:] + 324",
  "6   SJMediaCacheServer                  0x0000000108074090 __25-[FILEPrefetcher prepare]_block_invoke + 380",
  "7   libdispatch.dylib                   0x0000000109aa2b34 _dispatch_client_callout + 20",
  "8   libdispatch.dylib                   0x0000000109ab40b4 _dispatch_lane_barrier_sync_invoke_and_complete + 176",
  "9   SJMediaCacheServer                  0x00000001080b4f3c mcs_queue_sync + 88",
  "10  SJMediaCacheServer                  0x0000000108073efc -[FILEPrefetcher prepare] + 108",
  "11  SJMediaCacheServer                  0x00000001080b0f54 -[MCSPrefetchOperation start] + 1724",
  "12  Foundation                          0x000000018a2bfa9c C52A9630-60F1-3D48-A6C3-50A20DE78C6A + 490140",
  "13  Foundation                          0x000000018a2bf808 C52A9630-60F1-3D48-A6C3-50A20DE78C6A + 489480",
  "14  libdispatch.dylib                   0x0000000109aa0f50 _dispatch_call_block_and_release + 32",
  "15  libdispatch.dylib                   0x0000000109aa2b34 _dispatch_client_callout + 20",
  "16  libdispatch.dylib                   0x0000000109aa5c20 _dispatch_continuation_pop + 676",
  "17  libdispatch.dylib                   0x0000000109aa4ef8 _dispatch_async_redirect_invoke + 680",
  "18  libdispatch.dylib                   0x0000000109ab6cd8 _dispatch_root_queue_drain + 404",
  "19  libdispatch.dylib                   0x0000000109ab76cc _dispatch_worker_thread2 + 188",
  "20  libsystem_pthread.dylib             0x00000001f5293928 _pthread_wqthread + 228",
  "21  libsystem_pthread.dylib             0x00000001f5293a04 start_wqthread + 8"
]

**Comment by J0nphy** [comment]
![飞书20240203-112308](https://github.com/changsanjiang/SJMediaCacheServer/assets/10956434/eef0f687-93b8-4faf-b426-951281220e64)

**Comment by changsanjiang** [comment]
尝试新版 2.0.0
